### ISSUE TITLE
404 while getting http://crypto-js.googlecode.com

### ISSUE THREAD

**Issue by lucazen** [bobvann/RPirrigate#6]
Wild error appears at this point

settings.php:11 GET http://crypto-js.googlecode.com/svn/tags/3.1.2/build/rollups/md5.js 
settings.php:12 GET http://crypto-js.googlecode.com/svn/tags/3.1.2/build/rollups/sha1.js 

I suggest to include phisical files within the project.

**Comment by bobvann** [comment]
will include soon.

thanks!

**Comment by lucazen** [comment]
Ahm, you should include also the core.js, before these two.

Thank you for your awesome interface!

**Comment by bobvann** [comment]
https://github.com/bobvann/RPirrigate/commit/d6845b894683dcc31f964d362286c334e00c7b1c

**Comment by bobvann** [comment]
@lucazen let me know if it is working correctly now!

**Comment by lucazen** [comment]
@bobvann fixed! Thanks!
